# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\List.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_List(object):
    def setupUi(self, List):
        List.setObjectName("List")
        List.resize(524, 641)
        self.textBrowser = QtWidgets.QTextBrowser(List)
        self.textBrowser.setGeometry(QtCore.QRect(10, 95, 501, 531))
        self.textBrowser.setObjectName("textBrowser")
        self.label = QtWidgets.QLabel(List)
        self.label.setGeometry(QtCore.QRect(10, 10, 400, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.radioButton_Family = QtWidgets.QRadioButton(List)
        self.radioButton_Family.setGeometry(QtCore.QRect(180, 60, 121, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_Family.setFont(font)
        self.radioButton_Family.setObjectName("radioButton_Family")
        self.radioButton_name = QtWidgets.QRadioButton(List)
        self.radioButton_name.setGeometry(QtCore.QRect(80, 60, 88, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.radioButton_name.setFont(font)
        self.radioButton_name.setChecked(True)
        self.radioButton_name.setObjectName("radioButton_name")
        self.label_2 = QtWidgets.QLabel(List)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(List)
        QtCore.QMetaObject.connectSlotsByName(List)
        List.setTabOrder(self.radioButton_name, self.radioButton_Family)
        List.setTabOrder(self.radioButton_Family, self.textBrowser)

    def retranslateUi(self, List):
        _translate = QtCore.QCoreApplication.translate
        List.setWindowTitle(_translate("List", "Dialog"))
        self.label.setText(_translate("List", "Contacts List:"))
        self.radioButton_Family.setText(_translate("List", "Family Name"))
        self.radioButton_name.setText(_translate("List", "Name"))
        self.label_2.setText(_translate("List", "Sort:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    List = QtWidgets.QDialog()
    ui = Ui_List()
    ui.setupUi(List)
    List.show()
    sys.exit(app.exec_())
