# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Text.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Texts(object):
    def setupUi(self, Texts):
        Texts.setObjectName("Texts")
        Texts.resize(524, 641)
        self.textBrowser = QtWidgets.QTextBrowser(Texts)
        self.textBrowser.setGeometry(QtCore.QRect(20, 390, 491, 231))
        self.textBrowser.setObjectName("textBrowser")
        self.pushButton = QtWidgets.QPushButton(Texts)
        self.pushButton.setGeometry(QtCore.QRect(370, 300, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(Texts)
        self.label.setGeometry(QtCore.QRect(20, 10, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(Texts)
        self.textEdit.setGeometry(QtCore.QRect(20, 50, 491, 231))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(Texts)
        self.label_2.setGeometry(QtCore.QRect(20, 350, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Texts)
        QtCore.QMetaObject.connectSlotsByName(Texts)
        Texts.setTabOrder(self.textEdit, self.pushButton)
        Texts.setTabOrder(self.pushButton, self.textBrowser)

    def retranslateUi(self, Texts):
        _translate = QtCore.QCoreApplication.translate
        Texts.setWindowTitle(_translate("Texts", "Dialog"))
        self.pushButton.setText(_translate("Texts", "Find"))
        self.label.setText(_translate("Texts", "Enter Text:"))
        self.label_2.setText(_translate("Texts", "Names and Phone Numbers:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Texts = QtWidgets.QDialog()
    ui = Ui_Texts()
    ui.setupUi(Texts)
    Texts.show()
    sys.exit(app.exec_())
