# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Web.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_web(object):
    def setupUi(self, web):
        web.setObjectName("web")
        web.resize(524, 425)
        self.lineEdit_email = QtWidgets.QLineEdit(web)
        self.lineEdit_email.setGeometry(QtCore.QRect(140, 170, 361, 30))
        self.lineEdit_email.setObjectName("lineEdit_email")
        self.pushButton = QtWidgets.QPushButton(web)
        self.pushButton.setGeometry(QtCore.QRect(360, 330, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(web)
        self.label_2.setGeometry(QtCore.QRect(20, 90, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.lineEdit_Family = QtWidgets.QLineEdit(web)
        self.lineEdit_Family.setGeometry(QtCore.QRect(140, 130, 361, 30))
        self.lineEdit_Family.setObjectName("lineEdit_Family")
        self.label_3 = QtWidgets.QLabel(web)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 91, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.lineEdit_phone = QtWidgets.QLineEdit(web)
        self.lineEdit_phone.setGeometry(QtCore.QRect(140, 210, 361, 30))
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.label_errorshow = QtWidgets.QLabel(web)
        self.label_errorshow.setGeometry(QtCore.QRect(20, 250, 491, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_errorshow.setFont(font)
        self.label_errorshow.setText("")
        self.label_errorshow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_errorshow.setWordWrap(True)
        self.label_errorshow.setObjectName("label_errorshow")
        self.label_4 = QtWidgets.QLabel(web)
        self.label_4.setGeometry(QtCore.QRect(20, 170, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(web)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 111, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.lineEditName = QtWidgets.QLineEdit(web)
        self.lineEditName.setGeometry(QtCore.QRect(140, 90, 361, 30))
        self.lineEditName.setObjectName("lineEditName")
        self.label = QtWidgets.QLabel(web)
        self.label.setGeometry(QtCore.QRect(10, 20, 400, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(web)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 330, 141, 71))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(web)
        QtCore.QMetaObject.connectSlotsByName(web)
        web.setTabOrder(self.lineEditName, self.lineEdit_Family)
        web.setTabOrder(self.lineEdit_Family, self.lineEdit_email)
        web.setTabOrder(self.lineEdit_email, self.lineEdit_phone)
        web.setTabOrder(self.lineEdit_phone, self.pushButton_2)
        web.setTabOrder(self.pushButton_2, self.pushButton)

    def retranslateUi(self, web):
        _translate = QtCore.QCoreApplication.translate
        web.setWindowTitle(_translate("web", "Web Scraping"))
        self.pushButton.setText(_translate("web", "Add"))
        self.label_2.setText(_translate("web", "Name:"))
        self.label_3.setText(_translate("web", "Family Name:"))
        self.label_4.setText(_translate("web", "Email Address:"))
        self.label_5.setText(_translate("web", "Phone Number:"))
        self.label.setText(_translate("web", "Click to get data from site:"))
        self.pushButton_2.setText(_translate("web", "Get Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    web = QtWidgets.QDialog()
    ui = Ui_web()
    ui.setupUi(web)
    web.show()
    sys.exit(app.exec_())
