# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UiFiles\Save.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(610, 300)
        Dialog.setStyleSheet("background-color:#232323")
        self.pushButton_json = QtWidgets.QPushButton(Dialog)
        self.pushButton_json.setGeometry(QtCore.QRect(390, 150, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_json.setFont(font)
        self.pushButton_json.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_json.setStyleSheet("background-color:#318CE7; color:white")
        self.pushButton_json.setObjectName("pushButton_json")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(10, 30, 581, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:white;")
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setWordWrap(True)
        self.label_6.setObjectName("label_6")
        self.pushButton_txt = QtWidgets.QPushButton(Dialog)
        self.pushButton_txt.setGeometry(QtCore.QRect(250, 150, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_txt.setFont(font)
        self.pushButton_txt.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_txt.setStyleSheet("background-color:#318CE7; color:white")
        self.pushButton_txt.setObjectName("pushButton_txt")
        self.pushButton_xml = QtWidgets.QPushButton(Dialog)
        self.pushButton_xml.setGeometry(QtCore.QRect(110, 150, 101, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_xml.setFont(font)
        self.pushButton_xml.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_xml.setStyleSheet("background-color:#318CE7; color:white")
        self.pushButton_xml.setObjectName("pushButton_xml")
        self.label_error = QtWidgets.QLabel(Dialog)
        self.label_error.setGeometry(QtCore.QRect(10, 260, 591, 21))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label_error.setFont(font)
        self.label_error.setStyleSheet("color:#EB4C42;")
        self.label_error.setText("")
        self.label_error.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_error.setObjectName("label_error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_json.setText(_translate("Dialog", "JSON"))
        self.label_6.setText(_translate("Dialog", "Choose one file type below to save database in it"))
        self.pushButton_txt.setText(_translate("Dialog", "TXT"))
        self.pushButton_xml.setText(_translate("Dialog", "XML"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
