# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Dialog_Find.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogFind(object):
    def setupUi(self, DialogFind):
        DialogFind.setObjectName("DialogFind")
        DialogFind.resize(622, 751)
        self.widget = QtWidgets.QWidget(DialogFind)
        self.widget.setGeometry(QtCore.QRect(0, 0, 621, 751))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.0524476, y1:0.0909091, x2:1, y2:1, stop:0 rgba(209, 109, 165, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 581, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(10, 170, 601, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setPlainText("")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.widget)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(10, 480, 601, 261))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.plainTextEdit_2.setFont(font)
        self.plainTextEdit_2.setStyleSheet("background-color: rgb(229, 229, 229);")
        self.plainTextEdit_2.setReadOnly(True)
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.pushButtonFind = QtWidgets.QPushButton(self.widget)
        self.pushButtonFind.setGeometry(QtCore.QRect(510, 110, 91, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonFind.setFont(font)
        self.pushButtonFind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonFind.setStyleSheet("border-radius:20px;\n"
"background-color: rgb(33, 255, 181);")
        self.pushButtonFind.setCheckable(False)
        self.pushButtonFind.setAutoDefault(False)
        self.pushButtonFind.setDefault(False)
        self.pushButtonFind.setFlat(False)
        self.pushButtonFind.setObjectName("pushButtonFind")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 481, 51))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;font: 12pt \"B Nazanin\";")
        self.label_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(DialogFind)
        QtCore.QMetaObject.connectSlotsByName(DialogFind)
        DialogFind.setTabOrder(self.pushButtonFind, self.plainTextEdit)
        DialogFind.setTabOrder(self.plainTextEdit, self.plainTextEdit_2)

    def retranslateUi(self, DialogFind):
        _translate = QtCore.QCoreApplication.translate
        DialogFind.setWindowTitle(_translate("DialogFind", "Find Contacts From Text"))
        self.label.setText(_translate("DialogFind", "Contact Manager System"))
        self.plainTextEdit.setPlaceholderText(_translate("DialogFind", "Original Text ..."))
        self.plainTextEdit_2.setPlaceholderText(_translate("DialogFind", "Contact Info ..."))
        self.pushButtonFind.setText(_translate("DialogFind", "Find"))
        self.label_2.setText(_translate("DialogFind", "Click To Find Contacts\' Names and Phones"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogFind = QtWidgets.QDialog()
    ui = Ui_DialogFind()
    ui.setupUi(DialogFind)
    DialogFind.show()
    sys.exit(app.exec_())
