# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(622, 751)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 621, 751))
        self.widget.setStyleSheet("QWidget#widget{\n"
"background-color:qlineargradient(spread:pad, x1:0.0524476, y1:0.0909091, x2:1, y2:1, stop:0 rgba(209, 109, 165, 255), stop:1 rgba(255, 255, 255, 255))}")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 90, 581, 61))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(22)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        font.setKerning(True)
        self.label.setFont(font)
        self.label.setStyleSheet("color:white;")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 180, 581, 61))
        font = QtGui.QFont()
        font.setFamily("B Nazanin")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:white;")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButtonEdit = QtWidgets.QPushButton(self.widget)
        self.pushButtonEdit.setGeometry(QtCore.QRect(185, 260, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonEdit.setFont(font)
        self.pushButtonEdit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonEdit.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(115, 255, 255)")
        self.pushButtonEdit.setCheckable(False)
        self.pushButtonEdit.setAutoDefault(False)
        self.pushButtonEdit.setDefault(False)
        self.pushButtonEdit.setFlat(False)
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.pushButtonList = QtWidgets.QPushButton(self.widget)
        self.pushButtonList.setGeometry(QtCore.QRect(185, 340, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonList.setFont(font)
        self.pushButtonList.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonList.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(115, 255, 255)")
        self.pushButtonList.setObjectName("pushButtonList")
        self.pushButtonFind = QtWidgets.QPushButton(self.widget)
        self.pushButtonFind.setGeometry(QtCore.QRect(185, 420, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonFind.setFont(font)
        self.pushButtonFind.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonFind.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(115, 255, 255)")
        self.pushButtonFind.setObjectName("pushButtonFind")
        self.pushButtonWeb = QtWidgets.QPushButton(self.widget)
        self.pushButtonWeb.setGeometry(QtCore.QRect(185, 500, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonWeb.setFont(font)
        self.pushButtonWeb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonWeb.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(115, 255, 255)")
        self.pushButtonWeb.setObjectName("pushButtonWeb")
        self.pushButtonSave = QtWidgets.QPushButton(self.widget)
        self.pushButtonSave.setGeometry(QtCore.QRect(185, 580, 251, 51))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(10)
        self.pushButtonSave.setFont(font)
        self.pushButtonSave.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButtonSave.setStyleSheet("border-radius:20px;\n"
"background-color:rgb(115, 255, 255)")
        self.pushButtonSave.setObjectName("pushButtonSave")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Menu"))
        self.label.setText(_translate("MainWindow", "Contact Manager System"))
        self.label_2.setText(_translate("MainWindow", "Choose What You Love To Do"))
        self.pushButtonEdit.setText(_translate("MainWindow", "Edit Contacts"))
        self.pushButtonList.setText(_translate("MainWindow", "Contacts List"))
        self.pushButtonFind.setText(_translate("MainWindow", "Contact Finder"))
        self.pushButtonWeb.setText(_translate("MainWindow", "Get Contact From Web"))
        self.pushButtonSave.setText(_translate("MainWindow", "Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
