# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Table.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogTa(object):
    def setupUi(self, DialogTa):
        DialogTa.setObjectName("DialogTa")
        DialogTa.resize(630, 737)
        DialogTa.setStyleSheet("background-color:#676767")
        self.checkBox = QtWidgets.QCheckBox(DialogTa)
        self.checkBox.setGeometry(QtCore.QRect(30, 110, 111, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setStyleSheet("color:#FFDB00")
        self.checkBox.setChecked(True)
        self.checkBox.setTristate(False)
        self.checkBox.setObjectName("checkBox")
        self.checkBox_2 = QtWidgets.QCheckBox(DialogTa)
        self.checkBox_2.setGeometry(QtCore.QRect(150, 110, 141, 19))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color:#FFDB00")
        self.checkBox_2.setTristate(False)
        self.checkBox_2.setObjectName("checkBox_2")
        self.tableWidget = QtWidgets.QTableWidget(DialogTa)
        self.tableWidget.setGeometry(QtCore.QRect(20, 140, 591, 581))
        self.tableWidget.setStyleSheet("color:white")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(130)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.label = QtWidgets.QLabel(DialogTa)
        self.label.setGeometry(QtCore.QRect(10, 30, 611, 61))
        font = QtGui.QFont()
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#FFDB00")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        self.retranslateUi(DialogTa)
        QtCore.QMetaObject.connectSlotsByName(DialogTa)

    def retranslateUi(self, DialogTa):
        _translate = QtCore.QCoreApplication.translate
        DialogTa.setWindowTitle(_translate("DialogTa", "Table"))
        self.checkBox.setText(_translate("DialogTa", "Sort By Name"))
        self.checkBox_2.setText(_translate("DialogTa", "Sort By Last Name"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("DialogTa", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("DialogTa", "Last Name"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("DialogTa", "Number"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("DialogTa", "Email"))
        self.label.setText(_translate("DialogTa", "Contact Manageing System"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogTa = QtWidgets.QDialog()
    ui = Ui_DialogTa()
    ui.setupUi(DialogTa)
    DialogTa.show()
    sys.exit(app.exec_())
